#
# config_local.yaml - configuration local for the example
#
#


db:
    protocol : "http"
    host : "ENTER-HERE-THE-COUCH-DB-HOSTNAME" 
    port : 5984
    username : "admin"
    password : "SECRET"
    db : "corpus"

# enter here the hours the webcrawler should be alive
working_hours : [ 1, 2, 3, 4, 5, 6, 7 ]
working_hours_extract_words : [  0,  
                  8,  9, 10, 11, 
                  12, 13, 14, 15, 
                  16, 17, 18, 19, 
                  20, 21, 22, 23 ]

# maximum jobs to run in paralell
max_jobs : 8

# what user agent the crawler must show on requests
user_agent: "spanish corpus project"

# where do you want the resulting corpus files
# will be created??? Every time you run 
# "corpus_extractor" these files will be 
# overwritten
corpus_result_dir : "/home/rluna/tmp"



